language: bash

script:
  - export CIUTL_BRANCH=$TRAVIS_BRANCH
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then export CIUTL_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
  - sh <(curl -L https://raw.githubusercontent.com/takemikami/ci-utils/$CIUTL_BRANCH/install.sh) $CIUTL_BRANCH
  - export PATH=$PATH:$HOME/.ci-utils/bin
  - ciutils github_post_status -s success -u "https://github.com/takemikami/ci-utils" -d "success of ciutils-test" -c "ciutiltest-from-travis"
