version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      # setup ci-utils
      - run:
          name: install curl
          command: apt-get update && apt-get install -y curl jq
      - run:
          name: install ci-utils
          command: |
            curl -L https://raw.githubusercontent.com/takemikami/ci-utils/installer/install.sh | sh
            echo 'export PATH=$PATH:$HOME/.ci-utils/bin' >> $BASH_ENV
            source $BASH_ENV

      - checkout
